import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/navbar/TopBar";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <Navbar />
        <AntdRegistry>{children}</AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}
